### ISSUE TITLE
[BUG] Move UI_Metadata from state to GC index. 

### ISSUE THREAD

**Issue by amitgalitz** [opensearch-project/opensearch-ai-flow-framework#135]
### What is the bug?
We currently store the UI metadata in the state index which doesn't really follow the pattern we have where the GC refers to the object itself and the state refers to the active workflow. We should move UI metadata back to the global context index as that is also what the frontend will be searching over.

**Comment by owaiskazi19** [comment]
Missed that we have an issue. Created https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/140 with the solution.
