### ISSUE TITLE
[FEATURE] Move UI Metadata from State Index to Global Context Index

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-ai-flow-framework#140]
### Is your feature request related to a problem?
We moved `UI_METADATA_FIELD` to state index recently [here](https://github.com/opensearch-project/opensearch-ai-flow-framework/pull/110/files#diff-d49816ce76f874e242a545dd3de0515c2435ec7a6a315faf83ae28e4069f08e0R321). The Search APIs as a part of https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/124 searches on GC index. For frontend to utilize the search APIs, the `UI_METADATA_FIELD` should be moved to GC index back.

### What solution would you like?
1. Move `UI_METADATA_FIELD` field to GC index.
2. See if the request came from dashboard based on user-agents [here](https://github.com/opensearch-project/opensearch-ai-flow-framework/pull/139/files#diff-60d4924f5a70806d00988d81fdcd27d050a1d09ecb925cfa9b4449bb7bd224eeR35) and include `UI_METADATA_FIELD`.
3. Else, exclude `UI_METADATA_FIELD`.

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by joshpalis** [comment]
There's already an issue for this : https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/135

**Comment by owaiskazi19** [comment]
> There's already an issue for this : #135

Ah! I'll close #135
