### ISSUE TITLE
[FEATURE] Validate a process flow graph

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-ai-flow-framework#18]
### Is your feature request related to a problem?

The result of https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/17 will be an ordered collection of nodes.  However, there may be invalid connections in this sequence.  

### What solution would you like?
Perform error-handling to identify these invalid connections, throwing verbose exceptions explaining the reason.  Validation checks should include:
 - Type-checking of output vs. input at at least a high level (text vs. binary data)
 - Type-checking of output vs. input at a more detailed level if available (required attributes)
 - All nodes have a predecessor and dependent node 

### Do you have any additional context?

The type checking would ideally tie into Java inheritance concepts.

**Comment by minalsha** [comment]
This will be covered as part of https://github.com/opensearch-project/opensearch-ai-flow-framework/issues/88.
