### ISSUE TITLE
[FEATURE] Create Status API

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-ai-flow-framework#22]
### Is your feature request related to a problem?
Implement a GET API to fetch the status of the workflow setup. This API will be used to get information from the state index.

### What solution would you like?
We will have a status api that by default just gives state, provisioning progress and error information
When _all=true it will return all the info back thats stored in the state and GC index. 

```
GET _plugins/ai-flow/workflows/<workflowId>/_status
Response:

{
    "state": "FAILED",
    "error": "Some error message"
}
```
```
GET _plugins/ai-flow/workflows/<workflowId>/_status?_all=true
{
"state_id" : "3Dh6TXwBwf_U8gjURE0F"
"state": "RUNNING",
"error": "",
"provisioning_progress" : "IN_PROGRESS",
"provision_start_time": 1633399991933,
"provision_end_time": 163400401933,
"user": {
"name": "admin",
"backend_roles": [
"admin"
],
"roles": [
"own_index",
"all_access"
],
"custom_attribute_names": [],
"user_requested_tenant": "__user__"
}
"template": {
    "EVERYTHING IN THE USE CASE TEMPLATE"
}, //...Future fields:
{
 "ingest calls": 30,
 "search_calls": 3000,
 "search_failure_count": 0,
 "ingest_failure_count": 0,
  "last_update_time": {
      "type": "date",
      "format": "strict_date_time||epoch_millis"
    },
    "started_by": {
      "type": "keyword"
    },
    "stopped_by": {
      "type": "keyword"
    },
 }
```

### Do you have any additional context?
This API would keep on evolving based on the requirement from frontend.

**Comment by owaiskazi19** [comment]
@amitgalitz will this API support status of each workflow step or just one status for the complete provisioning?

**Comment by amitgalitz** [comment]
> @amitgalitz will this API support status of each workflow step or just one status for the complete provisioning? Also, in the response we need to output `resources_created`, that's the only way user will get the response of the provisioning when the status is `COMPLETED` of the API.

For first iteration I wont have each workflow step status, especially since these steps are so fast, I will have the error tho for exact step that failed. I can add the `resources_created` to the base response though here.
