### ISSUE TITLE
[BUG] ProcessNodeTest is flaky on CI

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-ai-flow-framework#50]
### What is the bug?
The below test passes on local but fails on CI.
```
org.opensearch.flowframework.template.ProcessNodeTests > testNode FAILED
    java.lang.AssertionError
        at __randomizedtesting.SeedInfo.seed([9B313DC0540DBCB3:C8934CDC5B151A88]:0)
        at org.junit.Assert.fail(Assert.java:87)
        at org.junit.Assert.assertTrue(Assert.java:42)
        at org.junit.Assert.assertTrue(Assert.java:53)
        at org.opensearch.flowframework.template.ProcessNodeTests.testNode(ProcessNodeTests.java:56)
  1> [2023-09-22T00:46:59,576][INFO ][o.o.f.t.ProcessNodeTests ] [testNode] before test
  1> [2023-09-22T00:46:59,767][INFO ][o.o.f.t.ProcessNode      ] [[Thread-6]] >>> Starting A.
  1> [2023-09-22T00:46:59,805][INFO ][o.o.f.t.ProcessNodeTests ] [testNode] after test
        at __randomizedtesting.SeedInfo.seed([9B313DC0540DBCB3:C8934CDC5B151A88]:0)
```

This fails on CI when checking whether future is complete on 
```
        assertTrue(f.isDone());
```

### How can one reproduce the bug?
1. Run tests on Github CI
```
./gradlew ':test' --tests "org.opensearch.flowframework.template.ProcessNodeTests.testNode" -Dtests.seed=9B313DC0540DBCB3 -Dtests.security.manager=false -Dtests.locale=en-US -Dtests.timezone=Europe/Moscow -Druntime.java=17
```

### What is the expected behavior?
Test should pass

**Comment by dbwiddis** [comment]
This test should probably be removed from `ProcessNode`.  As noted in comments, it is more properly tested by a IT.  

Also, I expect I will be able to make the test pass when #42 is implemented, which requires one of the multiple PRs implementing `createComponents()` to get merged.  

Recommend commenting it out and tagging either this issue or #42 to re-enable it.

**Comment by dbwiddis** [comment]
So implementing #42 didn't fix this, but it turns out using `orTimeout()` on a future in the test class is somehow incompatible with the randomized testing we use.
