### ISSUE TITLE
[FEATURE] Create GlobalContext Index to Store Use-case Template information

### ISSUE THREAD

**Issue by jackiehanyang** [opensearch-project/opensearch-ai-flow-framework#51]
### Is your feature request related to a problem?
When receiving a use-case template from the frontend, we need a location to store information about the template. This ensures global access, allowing subsequent executions to query this information. 

### What solution would you like?
We are going to create an OpenSearch Index called the `GlobalContext` index to store this use-case template. The index mapping largely aligns with the use-case template fields, except for an additional field named `resource_created`. This field keeps a record of all resources that have been created during the process. This makes it easier for us to clean up resources later when the workflow is deleted. 

The `workflow` field value of the use-case template will be stored as a string in the `GlobalContext` index to avoid limitations imposed by the index mapping type. 

The `responses` field in the index mapping will store only the API responses mentioned in the `global_context` field of the use-case template. This ensures that subsequent executions can more easily look up the values they need.

```
{
    "dynamic": false,
    "_meta": {
        "schema_version": 1
    },
    "properties": {
        "workflow_id": {
            "type": "keyword"
        },
        "name": {
            "type": "text",
            "fields": {
                "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                }
            }
        },
        "description": {
            "type": "text"
        },
        "use_case": {
            "type": "keyword"
        },
        "operations": {
            "type": "keyword"
        },
        "version": {
            "type": "nested",
            "properties": {
                "template": {
                    "type": "integer"
                },
                "compatibility": {
                    "type": "integer"
                }
            }
        },
        "user_inputs": {
            "type": "nested",
            "properties": {
                "model_id": {
                    "type": "keyword"
                },
                "input_field": {
                    "type": "keyword"
                },
                "output_field": {
                    "type": "keyword"
                },
                "ingest_pipeline_name": {
                    "type": "keyword"
                },
                "index_name": {
                    "type": "keyword"
                }
            }
        },
        "workflows": {
            "type": "text"
        },
        "responses": {
            "type": "text"
        },
        "resources_created": {
            "type": "text"
        }  
    }
}
```
**Do you have any additional context?**
Later, we will have a separate index to store information related to workflow states for the Stats API to use.

**Comment by minalsha** [comment]
@jackiehanyang I am closing this issue since https://github.com/opensearch-project/opensearch-ai-flow-framework/pull/65 is merged.
